---
# Основной конфигурационный файл приложения "Заполнятор 3000"


app_name:
  label: Название приложения (отображается в заголовке окна и верхней части формы)
  value: KZVG - Заполнятор 3000

app_logo:
  label: Логотип приложения (отображается в верхней части формы)
  value: PNG_210619_kzvg-logo-name-transp.png

res_folder:
  label: Папка для ресурсов (изображений, в т.ч. лого)
  value: res/

in_folder:
  label: Папка с конфигами и шаблонами документов
  value: in/

out_folder_docx:
  label: Папка для выгрузки заполненных документов
  value: out/docx/

out_folder_data:
  label: Папка для выгрузки запоненных в форме полей в .yaml
  value: out/data/

doc_config_default:
  label: Стандартный конфигурационный файл для построения формы и выгрузки заполненного документа
  value: contract_config.yaml
